### ISSUE TITLE
图源问题

### ISSUE THREAD

**Issue by blackcatsama** [EternalSoySauce/Konachan#12]
sankaku的图有时候也加载不出来呢，有时候我下载的视频都是不完整的= =

**Comment by EternalSoySauce** [comment]
更新下 1.8.12
修复了sankaku解析、下载图片异常。该站现在限制了同个IP的访问速度，如遇到加载不出来的情况请稍等两三分钟后再试。
下载视频不完整应该是在挪文件的时候出现的异常，这版本也优化了一下，再看看还有没问题

**Comment by blackcatsama** [comment]
谢谢大大！大大辛苦啦><
