### ISSUE TITLE
Danbooru图源问题

### ISSUE THREAD

**Issue by Yanchuu** [EternalSoySauce/Konachan#17]
即使是美国节点全局访问，依旧加载失败，但是直接访问官网可以加载。

**Comment by EternalSoySauce** [comment]
k站加了防爬虫的机器人检测，还不知道怎么绕



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月24日(周一) 上午8:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [EternalSoySauce/Konachan] Danbooru图源问题 (Issue #17)




 
即使是美国节点全局访问，依旧加载失败，但是直接访问官网可以加载。

**Comment by EternalSoySauce** [comment]
v1.9.1优化了，终于有空维护了 QAQ
