### ISSUE TITLE
I can't set wallpaper 

### ISSUE THREAD

**Issue by iliaswo** [EternalSoySauce/Konachan#2]
please add set wallpaper future

**Comment by EternalSoySauce** [comment]
try to use v1.7.1
I have added custom cropping wallpapers future to fit more devices in this version.

**Comment by myace250** [comment]
没有适配Android10打不开

**Comment by EternalSoySauce** [comment]
确实没适配10。。我尽快找部测试机试试


 
---Original---

**Comment by EternalSoySauce** [comment]
你的是什么品牌手机


 
---Original---

**Comment by myace250** [comment]
> 你的是什么品牌手机
> […](#)
> ---原始---来自：“ myace250” <notifications@github.com> 日期：2019年11月7日，星期四，下午15:32收件人：“ EternalSoySauce / Konachan” <Konachan@noreply.github.com> ;; 抄送：“ EternalSoySauce” <1018717197@qq.com> ;;“评论” <comment@noreply.github.com> ;; 主题：回复：[EternalSoySauce / Konachan]我无法设置壁纸（[＃2](https://github.com/EternalSoySauce/Konachan/issues/2)）没有适应Android10打不开-您收到此评论是因为您发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。

华为mate30

**Comment by EternalSoySauce** [comment]
一时半会弄不到mate30测试机，我用谷歌pixel安卓10测是没问题的，暂时没法解决，对不住了 T_T


 
---Original---

**Comment by myace250** [comment]
应该是适配问题吧隔壁番库刚刚更新适配了安卓10以后就没有闪退了，谷歌是源生安卓10不闪退正常华为小米这些是魔改的安卓10

**Comment by EternalSoySauce** [comment]
那我找找国产安卓10。。主要公司还没买这些测试机，我自己也没有 XD



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "myace250"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 晚上9:23
收件人: "EternalSoySauce/Konachan"<Konachan@noreply.github.com&gt;; 
抄送: "zero"<1018717197@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [EternalSoySauce/Konachan] I can&#39;t set wallpaper  (#2)




应该是适配问题吧隔壁番库刚刚更新适配了安卓10以后就没有闪退了，谷歌是源生安卓10不闪退正常华为小米这些是魔改的安卓10

**Comment by EternalSoySauce** [comment]
> 应该是适配问题吧隔壁番库刚刚更新适配了安卓10以后就没有闪退了，谷歌是源生安卓10不闪退正常华为小米这些是魔改的安卓10

已经发布了新版本，首页看下链接，v1.7.2

**Comment by myace250** [comment]
不闪退，能康了

**Comment by myace250** [comment]
我得法，突然发现一个严重的问题刘海屏把滑稽藏起来了😂

**Comment by EternalSoySauce** [comment]
> 我得法，突然发现一个严重的问题刘海屏把滑稽藏起来了

嗯，这bug是最近突然出现的，没解掉。你退出重进，不切换图集页面就不会把滑稽藏起来了。闪退这比较急先改了，滑稽再等等 XD

**Comment by myace250** [comment]
分屏解决了，没茅台

**Comment by EternalSoySauce** [comment]
> 分屏解决了，没茅台

hhhhh，这解法可以的
