### ISSUE TITLE
[Feature Request] 图片页新增类似图集首页的展示模式

### ISSUE THREAD

**Issue by TakChen** [EternalSoySauce/Konachan#23]
目前图片页展示模式有两种,
![image](https://github.com/EternalSoySauce/Konachan/assets/10719409/d96a7c1e-13d4-4af7-86c1-12ade3a11390)
![image](https://github.com/EternalSoySauce/Konachan/assets/10719409/91673d17-7a3b-4ae3-a8b9-f1bd58554f7d)
希望能新增一种展示模式,  就是 图集页的这种展示模式
![image](https://github.com/EternalSoySauce/Konachan/assets/10719409/2c25372a-75a8-48da-86a3-546d50241f92)

感谢🫶🫶

**Comment by EternalSoySauce** [comment]
啊？首页展示缩略图不就是为了能一目了然看更多图片吗？展示成图集那样体验感不会很好噢。。已有的这两种展示方式只是为了适应竖版图片的图站，每行的数量也不是固定2个，是根据屏幕宽度自适应的

**Comment by TakChen** [comment]
可能是 浏览的目的不一样吧, 
我猜 目前现有的两种视图是为了更好地**找**图, 
而我提出这个请求 是因为 想更方便地**看**图;
虽然我可以点进图片详情页看大图, 但是 不断点击下方的切换 会有点繁琐, 远不够 直接滑动方便

**Comment by EternalSoySauce** [comment]
图片页展示的都是低清缩略图噢，放大会更模糊的。如果要是首页展示详情页高清图的话，会加载很久的，而且素材还有GIF、视频这种大文件

**Comment by TakChen** [comment]
理解, 那我就不再对此需求多追问了; 
那么换个角度, 能不能对图片详情页的上一张下一张的操作做个优化呢? 
目前是 屏幕底部 两边两个箭头切换的(而且位置不可调), 会考虑添加滑动手势来切换吗? 或者将箭头位置变成可调整?

**Comment by EternalSoySauce** [comment]
这个没问题，等过两天放年假了我带着几个todo一起更新一版

**Comment by TakChen** [comment]
感谢🙇‍
我这边另外开一个PR记录一下这个图片详情页的需求
