### ISSUE TITLE
[Feature Request/Enhancement] 图片详情页上/下一张切换方式优化

### ISSUE THREAD

**Issue by TakChen** [EternalSoySauce/Konachan#24]
目前是 屏幕底部 两边两个箭头切换的(而且位置不可调), 会考虑添加滑动手势来切换吗? 或者将箭头位置变成可调整?

_Originally posted by @TakChen in https://github.com/EternalSoySauce/Konachan/issues/23#issuecomment-1910194527_

**Comment by TakChen** [comment]
Possible Duplicate #18

**Comment by TakChen** [comment]
Scheduled

              这个没问题，等过两天放年假了我带着几个todo一起更新一版

_Originally posted by @EternalSoySauce in https://github.com/EternalSoySauce/Konachan/issues/23#issuecomment-1910208113_

**Comment by EternalSoySauce** [comment]
v1.9.3
